version: '3'

services:
  soa:
    image: saitam/soa_externe:latest
    #build: .
    domainname: wt1-8.ephec-ti.be
    container_name: soa_externe
    ports:
        - "53:53/tcp"
        - "53:53/udp"
