version: '3'

services:
 soa:
    image: saitam/soa_interne:latest
    domainname: internal
    container_name: soa_interne
    ports:
        - "53:53/tcp"
        - "53:53/udp"
    dns: 172.16.0.3
    dns_search: intranet
    networks:
      custom_network:
        ipv4_address: 172.16.0.3
        
networks:
  custom_network:
    external:
      name: intranet
