version: '3'
services:
  frontendintraweb:
   image: saitam/web_intra:latest
   ports:
    - 80:80
   networks:
     intranet:
       ipv4_address: 172.16.0.4
   restart: always
   container_name: test
networks:
  intranet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/24
