version: '2'
services:
  asterisk:
    container_name: voip
    image: saitam/voip:latest
    ports:
     - "5060:5060/udp"
     - "5060:5060/tcp"
     - "10000-10099:10000-10099/udp"
     - "8088:8088"
     - "8089:8089"
