version: '3'

services:
 user1:
    image: saitam/user:latest
    container_name: administration
    dns: 
    - 172.16.0.2
    dns_search: intranet
    tty: true
    networks:
      administration:
        ipv4_address: 172.16.2.1
        
networks:
  administration:
    external:
      name: administration
